apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gunit
  description: A cool go app
  annotations:
    backstage.io/kubernetes-id: gunit
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: cooktheryan/gunit
spec:
  type: app
  lifecycle: production
  owner: rhdh